spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/TestingDatabase
    username: mariaUser
    password: mariaPassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemisUser
    password: artemisPassword
  graphql:
    graphiql:
      enabled: true